CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`firstname` VARCHAR(100) NOT NULL DEFAULT '0',
	`lastname` VARCHAR(100) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=0;
